# Generated by Django 4.2.19 on 2025-09-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_alter_userprofile_level_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserstats',
            name='time_spent_today',
            field=models.IntegerField(default=0, help_text='Time spent active on the site today, in seconds.'),
        ),
    ]
