# Generated by Django 4.2.19 on 2025-09-15 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0007_dailyuserstats_time_spent_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_exercise_time',
            field=models.IntegerField(default=0, help_text='Total time spent in workouts, in seconds.'),
        ),
        migrations.CreateModel(
            name='UserSessionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Computed when the user logs out.')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Login date for daily aggregation.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_time'],
                'unique_together': {('user', 'session_key')},
            },
        ),
    ]
