# Generated by Django 4.2.19 on 2025-09-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_alter_userprofile_total_exercise_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyuserstats',
            name='workouts_today',
            field=models.IntegerField(default=0, help_text='Number of workouts completed today.'),
        ),
    ]
